CPP = g++ # компилятор
BIN_DIR = ChatClient/bin
FLAGS = -std=c++2a -stdlib=libc++ -fdiagnostics-color=always  # флаги компиляции
TARGETSRC = main.cpp # главный main файл
TARGET = chat # цель -> исполняемый файл
LIB = library.a # промежуточная библиотека
SOURCES = $(patsubst %.cpp,%,$(wildcard ./Project/*.cpp)) # файлы ресурсов ( Все cpp файлы в каталоге Project)

# Основная цель зависит от библиотеки lib
all: 	$(TARGETSRC) lib
		$(CPP) $(FLAGS) -o  $(PWD)/$(BIN_DIR)/$(TARGET) $(TARGETSRC) -L.  $(PWD)/$(BIN_DIR)/$(LIB)
		rm -rf $(SOURCES:=.o)  $(PWD)/$(BIN_DIR)/$(LIB)
lib: 					# В цикле создаем все объектные файлы
		mkdir -p  $(PWD)/$(BIN_DIR)
		$(foreach file,$(SOURCES),\
		$(CPP) $(FLAGS) -c -o $(file).o $(file).cpp ;)
		ar rc  $(PWD)/$(BIN_DIR)/$(LIB) $(SOURCES:=.o) 

install: all
	mkdir -p ~/Desktop/$(BIN_DIR)
	install $(PWD)/$(BIN_DIR)/$(TARGET) ~/Desktop/$(BIN_DIR)

uninstall: 
	rm -rf ~/Desktop/$(TARGET)

print-%  : ; @echo $* = $($*) #для вывода в консоль значения переменных (для теста использовал) -> make -f makefile print-SOURCES

